name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: mkdir build && make
    - name: unit-test
      run: |
        if [ $(cat ${{ secrets.EXAMPLE_CHALLENGE }} | build/aoc23-d1-c1) -eq ${{ secrets.EXAMPLE_ANSWER }} ]; then exit 0; else exit 1; fi
        if [ $(cat ${{ secrets.CHALLENGE }} | build/aoc23-d1-c1) -eq ${{ secrets.ANSWER }} ]; then exit 0; else exit 1; fi
